// // Copyright (c) 2026 StampCommit. All rights reserved.
// // GENERATED FILE — DO NOT EDIT.
// // Regenerate with: dart run pigeon --input pigeons/usb_messages.dart
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "usb_messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_zpl_printer {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// UsbDeviceRecord

UsbDeviceRecord::UsbDeviceRecord(
  int64_t vendor_id,
  int64_t product_id,
  const std::string& path,
  bool has_permission)
 : vendor_id_(vendor_id),
    product_id_(product_id),
    path_(path),
    has_permission_(has_permission) {}

UsbDeviceRecord::UsbDeviceRecord(
  int64_t vendor_id,
  int64_t product_id,
  const std::string& path,
  bool has_permission,
  const std::string* manufacturer,
  const std::string* product,
  const std::string* serial_number,
  const int64_t* interface_number,
  const int64_t* bulk_in_endpoint,
  const int64_t* bulk_out_endpoint,
  const int64_t* w_max_packet_size_out,
  const std::string* driver_binding)
 : vendor_id_(vendor_id),
    product_id_(product_id),
    path_(path),
    has_permission_(has_permission),
    manufacturer_(manufacturer ? std::optional<std::string>(*manufacturer) : std::nullopt),
    product_(product ? std::optional<std::string>(*product) : std::nullopt),
    serial_number_(serial_number ? std::optional<std::string>(*serial_number) : std::nullopt),
    interface_number_(interface_number ? std::optional<int64_t>(*interface_number) : std::nullopt),
    bulk_in_endpoint_(bulk_in_endpoint ? std::optional<int64_t>(*bulk_in_endpoint) : std::nullopt),
    bulk_out_endpoint_(bulk_out_endpoint ? std::optional<int64_t>(*bulk_out_endpoint) : std::nullopt),
    w_max_packet_size_out_(w_max_packet_size_out ? std::optional<int64_t>(*w_max_packet_size_out) : std::nullopt),
    driver_binding_(driver_binding ? std::optional<std::string>(*driver_binding) : std::nullopt) {}

int64_t UsbDeviceRecord::vendor_id() const {
  return vendor_id_;
}

void UsbDeviceRecord::set_vendor_id(int64_t value_arg) {
  vendor_id_ = value_arg;
}


int64_t UsbDeviceRecord::product_id() const {
  return product_id_;
}

void UsbDeviceRecord::set_product_id(int64_t value_arg) {
  product_id_ = value_arg;
}


const std::string& UsbDeviceRecord::path() const {
  return path_;
}

void UsbDeviceRecord::set_path(std::string_view value_arg) {
  path_ = value_arg;
}


bool UsbDeviceRecord::has_permission() const {
  return has_permission_;
}

void UsbDeviceRecord::set_has_permission(bool value_arg) {
  has_permission_ = value_arg;
}


const std::string* UsbDeviceRecord::manufacturer() const {
  return manufacturer_ ? &(*manufacturer_) : nullptr;
}

void UsbDeviceRecord::set_manufacturer(const std::string_view* value_arg) {
  manufacturer_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_manufacturer(std::string_view value_arg) {
  manufacturer_ = value_arg;
}


const std::string* UsbDeviceRecord::product() const {
  return product_ ? &(*product_) : nullptr;
}

void UsbDeviceRecord::set_product(const std::string_view* value_arg) {
  product_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_product(std::string_view value_arg) {
  product_ = value_arg;
}


const std::string* UsbDeviceRecord::serial_number() const {
  return serial_number_ ? &(*serial_number_) : nullptr;
}

void UsbDeviceRecord::set_serial_number(const std::string_view* value_arg) {
  serial_number_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_serial_number(std::string_view value_arg) {
  serial_number_ = value_arg;
}


const int64_t* UsbDeviceRecord::interface_number() const {
  return interface_number_ ? &(*interface_number_) : nullptr;
}

void UsbDeviceRecord::set_interface_number(const int64_t* value_arg) {
  interface_number_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_interface_number(int64_t value_arg) {
  interface_number_ = value_arg;
}


const int64_t* UsbDeviceRecord::bulk_in_endpoint() const {
  return bulk_in_endpoint_ ? &(*bulk_in_endpoint_) : nullptr;
}

void UsbDeviceRecord::set_bulk_in_endpoint(const int64_t* value_arg) {
  bulk_in_endpoint_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_bulk_in_endpoint(int64_t value_arg) {
  bulk_in_endpoint_ = value_arg;
}


const int64_t* UsbDeviceRecord::bulk_out_endpoint() const {
  return bulk_out_endpoint_ ? &(*bulk_out_endpoint_) : nullptr;
}

void UsbDeviceRecord::set_bulk_out_endpoint(const int64_t* value_arg) {
  bulk_out_endpoint_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_bulk_out_endpoint(int64_t value_arg) {
  bulk_out_endpoint_ = value_arg;
}


const int64_t* UsbDeviceRecord::w_max_packet_size_out() const {
  return w_max_packet_size_out_ ? &(*w_max_packet_size_out_) : nullptr;
}

void UsbDeviceRecord::set_w_max_packet_size_out(const int64_t* value_arg) {
  w_max_packet_size_out_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_w_max_packet_size_out(int64_t value_arg) {
  w_max_packet_size_out_ = value_arg;
}


const std::string* UsbDeviceRecord::driver_binding() const {
  return driver_binding_ ? &(*driver_binding_) : nullptr;
}

void UsbDeviceRecord::set_driver_binding(const std::string_view* value_arg) {
  driver_binding_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UsbDeviceRecord::set_driver_binding(std::string_view value_arg) {
  driver_binding_ = value_arg;
}


EncodableList UsbDeviceRecord::ToEncodableList() const {
  EncodableList list;
  list.reserve(12);
  list.push_back(EncodableValue(vendor_id_));
  list.push_back(EncodableValue(product_id_));
  list.push_back(EncodableValue(path_));
  list.push_back(EncodableValue(has_permission_));
  list.push_back(manufacturer_ ? EncodableValue(*manufacturer_) : EncodableValue());
  list.push_back(product_ ? EncodableValue(*product_) : EncodableValue());
  list.push_back(serial_number_ ? EncodableValue(*serial_number_) : EncodableValue());
  list.push_back(interface_number_ ? EncodableValue(*interface_number_) : EncodableValue());
  list.push_back(bulk_in_endpoint_ ? EncodableValue(*bulk_in_endpoint_) : EncodableValue());
  list.push_back(bulk_out_endpoint_ ? EncodableValue(*bulk_out_endpoint_) : EncodableValue());
  list.push_back(w_max_packet_size_out_ ? EncodableValue(*w_max_packet_size_out_) : EncodableValue());
  list.push_back(driver_binding_ ? EncodableValue(*driver_binding_) : EncodableValue());
  return list;
}

UsbDeviceRecord UsbDeviceRecord::FromEncodableList(const EncodableList& list) {
  UsbDeviceRecord decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<std::string>(list[2]),
    std::get<bool>(list[3]));
  auto& encodable_manufacturer = list[4];
  if (!encodable_manufacturer.IsNull()) {
    decoded.set_manufacturer(std::get<std::string>(encodable_manufacturer));
  }
  auto& encodable_product = list[5];
  if (!encodable_product.IsNull()) {
    decoded.set_product(std::get<std::string>(encodable_product));
  }
  auto& encodable_serial_number = list[6];
  if (!encodable_serial_number.IsNull()) {
    decoded.set_serial_number(std::get<std::string>(encodable_serial_number));
  }
  auto& encodable_interface_number = list[7];
  if (!encodable_interface_number.IsNull()) {
    decoded.set_interface_number(std::get<int64_t>(encodable_interface_number));
  }
  auto& encodable_bulk_in_endpoint = list[8];
  if (!encodable_bulk_in_endpoint.IsNull()) {
    decoded.set_bulk_in_endpoint(std::get<int64_t>(encodable_bulk_in_endpoint));
  }
  auto& encodable_bulk_out_endpoint = list[9];
  if (!encodable_bulk_out_endpoint.IsNull()) {
    decoded.set_bulk_out_endpoint(std::get<int64_t>(encodable_bulk_out_endpoint));
  }
  auto& encodable_w_max_packet_size_out = list[10];
  if (!encodable_w_max_packet_size_out.IsNull()) {
    decoded.set_w_max_packet_size_out(std::get<int64_t>(encodable_w_max_packet_size_out));
  }
  auto& encodable_driver_binding = list[11];
  if (!encodable_driver_binding.IsNull()) {
    decoded.set_driver_binding(std::get<std::string>(encodable_driver_binding));
  }
  return decoded;
}

// UsbEnumerateFilter

UsbEnumerateFilter::UsbEnumerateFilter(bool include_descriptor_strings)
 : include_descriptor_strings_(include_descriptor_strings) {}

UsbEnumerateFilter::UsbEnumerateFilter(
  const int64_t* vendor_id,
  bool include_descriptor_strings)
 : vendor_id_(vendor_id ? std::optional<int64_t>(*vendor_id) : std::nullopt),
    include_descriptor_strings_(include_descriptor_strings) {}

const int64_t* UsbEnumerateFilter::vendor_id() const {
  return vendor_id_ ? &(*vendor_id_) : nullptr;
}

void UsbEnumerateFilter::set_vendor_id(const int64_t* value_arg) {
  vendor_id_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void UsbEnumerateFilter::set_vendor_id(int64_t value_arg) {
  vendor_id_ = value_arg;
}


bool UsbEnumerateFilter::include_descriptor_strings() const {
  return include_descriptor_strings_;
}

void UsbEnumerateFilter::set_include_descriptor_strings(bool value_arg) {
  include_descriptor_strings_ = value_arg;
}


EncodableList UsbEnumerateFilter::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(vendor_id_ ? EncodableValue(*vendor_id_) : EncodableValue());
  list.push_back(EncodableValue(include_descriptor_strings_));
  return list;
}

UsbEnumerateFilter UsbEnumerateFilter::FromEncodableList(const EncodableList& list) {
  UsbEnumerateFilter decoded(
    std::get<bool>(list[1]));
  auto& encodable_vendor_id = list[0];
  if (!encodable_vendor_id.IsNull()) {
    decoded.set_vendor_id(std::get<int64_t>(encodable_vendor_id));
  }
  return decoded;
}

// UsbOpenResult

UsbOpenResult::UsbOpenResult(
  int64_t platform_handle,
  int64_t vendor_id,
  int64_t product_id,
  int64_t claimed_interface_number,
  int64_t bulk_in_endpoint,
  int64_t bulk_out_endpoint,
  int64_t w_max_packet_size_out)
 : platform_handle_(platform_handle),
    vendor_id_(vendor_id),
    product_id_(product_id),
    claimed_interface_number_(claimed_interface_number),
    bulk_in_endpoint_(bulk_in_endpoint),
    bulk_out_endpoint_(bulk_out_endpoint),
    w_max_packet_size_out_(w_max_packet_size_out) {}

UsbOpenResult::UsbOpenResult(
  int64_t platform_handle,
  int64_t vendor_id,
  int64_t product_id,
  const std::string* serial_number,
  int64_t claimed_interface_number,
  int64_t bulk_in_endpoint,
  int64_t bulk_out_endpoint,
  int64_t w_max_packet_size_out)
 : platform_handle_(platform_handle),
    vendor_id_(vendor_id),
    product_id_(product_id),
    serial_number_(serial_number ? std::optional<std::string>(*serial_number) : std::nullopt),
    claimed_interface_number_(claimed_interface_number),
    bulk_in_endpoint_(bulk_in_endpoint),
    bulk_out_endpoint_(bulk_out_endpoint),
    w_max_packet_size_out_(w_max_packet_size_out) {}

int64_t UsbOpenResult::platform_handle() const {
  return platform_handle_;
}

void UsbOpenResult::set_platform_handle(int64_t value_arg) {
  platform_handle_ = value_arg;
}


int64_t UsbOpenResult::vendor_id() const {
  return vendor_id_;
}

void UsbOpenResult::set_vendor_id(int64_t value_arg) {
  vendor_id_ = value_arg;
}


int64_t UsbOpenResult::product_id() const {
  return product_id_;
}

void UsbOpenResult::set_product_id(int64_t value_arg) {
  product_id_ = value_arg;
}


const std::string* UsbOpenResult::serial_number() const {
  return serial_number_ ? &(*serial_number_) : nullptr;
}

void UsbOpenResult::set_serial_number(const std::string_view* value_arg) {
  serial_number_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void UsbOpenResult::set_serial_number(std::string_view value_arg) {
  serial_number_ = value_arg;
}


int64_t UsbOpenResult::claimed_interface_number() const {
  return claimed_interface_number_;
}

void UsbOpenResult::set_claimed_interface_number(int64_t value_arg) {
  claimed_interface_number_ = value_arg;
}


int64_t UsbOpenResult::bulk_in_endpoint() const {
  return bulk_in_endpoint_;
}

void UsbOpenResult::set_bulk_in_endpoint(int64_t value_arg) {
  bulk_in_endpoint_ = value_arg;
}


int64_t UsbOpenResult::bulk_out_endpoint() const {
  return bulk_out_endpoint_;
}

void UsbOpenResult::set_bulk_out_endpoint(int64_t value_arg) {
  bulk_out_endpoint_ = value_arg;
}


int64_t UsbOpenResult::w_max_packet_size_out() const {
  return w_max_packet_size_out_;
}

void UsbOpenResult::set_w_max_packet_size_out(int64_t value_arg) {
  w_max_packet_size_out_ = value_arg;
}


EncodableList UsbOpenResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(EncodableValue(platform_handle_));
  list.push_back(EncodableValue(vendor_id_));
  list.push_back(EncodableValue(product_id_));
  list.push_back(serial_number_ ? EncodableValue(*serial_number_) : EncodableValue());
  list.push_back(EncodableValue(claimed_interface_number_));
  list.push_back(EncodableValue(bulk_in_endpoint_));
  list.push_back(EncodableValue(bulk_out_endpoint_));
  list.push_back(EncodableValue(w_max_packet_size_out_));
  return list;
}

UsbOpenResult UsbOpenResult::FromEncodableList(const EncodableList& list) {
  UsbOpenResult decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<int64_t>(list[4]),
    std::get<int64_t>(list[5]),
    std::get<int64_t>(list[6]),
    std::get<int64_t>(list[7]));
  auto& encodable_serial_number = list[3];
  if (!encodable_serial_number.IsNull()) {
    decoded.set_serial_number(std::get<std::string>(encodable_serial_number));
  }
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        return CustomEncodableValue(UsbDeviceRecord::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 130: {
        return CustomEncodableValue(UsbEnumerateFilter::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(UsbOpenResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(UsbDeviceRecord)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<UsbDeviceRecord>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(UsbEnumerateFilter)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<UsbEnumerateFilter>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(UsbOpenResult)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<UsbOpenResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by UsbHostApi.
const flutter::StandardMessageCodec& UsbHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `UsbHostApi` to handle messages through the `binary_messenger`.
void UsbHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  UsbHostApi* api) {
  UsbHostApi::SetUp(binary_messenger, api, "");
}

void UsbHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  UsbHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.isSupported" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<bool> output = api->IsSupported();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.enumerate" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_filter_arg = args.at(0);
          if (encodable_filter_arg.IsNull()) {
            reply(WrapError("filter_arg unexpectedly null."));
            return;
          }
          const auto& filter_arg = std::any_cast<const UsbEnumerateFilter&>(std::get<CustomEncodableValue>(encodable_filter_arg));
          api->Enumerate(filter_arg, [reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.hasPermission" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_path_arg = args.at(0);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          ErrorOr<bool> output = api->HasPermission(path_arg);
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.requestPermission" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_path_arg = args.at(0);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->RequestPermission(path_arg, [reply](ErrorOr<bool>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.openForFfi" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_path_arg = args.at(0);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->OpenForFfi(path_arg, [reply](ErrorOr<UsbOpenResult>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.closeAfterFfi" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_path_arg = args.at(0);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->CloseAfterFfi(path_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue UsbHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue UsbHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace flutter_zpl_printer
