// // Copyright (c) 2026 StampCommit. All rights reserved.
// // GENERATED FILE — DO NOT EDIT.
// // Regenerate with: dart run pigeon --input pigeons/usb_messages.dart
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_USB_MESSAGES_G_H_
#define PIGEON_USB_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace flutter_zpl_printer {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class UsbHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// One USB device returned by [UsbHostApi.enumerate].
//
// Generated class from Pigeon that represents data sent in messages.
class UsbDeviceRecord {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit UsbDeviceRecord(
    int64_t vendor_id,
    int64_t product_id,
    const std::string& path,
    bool has_permission);

  // Constructs an object setting all fields.
  explicit UsbDeviceRecord(
    int64_t vendor_id,
    int64_t product_id,
    const std::string& path,
    bool has_permission,
    const std::string* manufacturer,
    const std::string* product,
    const std::string* serial_number,
    const int64_t* interface_number,
    const int64_t* bulk_in_endpoint,
    const int64_t* bulk_out_endpoint,
    const int64_t* w_max_packet_size_out,
    const std::string* driver_binding);

  // Vendor ID (0x0A5F for Zebra).
  int64_t vendor_id() const;
  void set_vendor_id(int64_t value_arg);

  // Product ID.
  int64_t product_id() const;
  void set_product_id(int64_t value_arg);

  // Platform-opaque identifier used for subsequent calls.
  // Android: `/dev/bus/usb/001/004`. macOS: IOKit path. Windows: `\\?\USB#VID_...`.
  const std::string& path() const;
  void set_path(std::string_view value_arg);

  // Android-relevant. True on macOS/Windows (permission model is per-app, not per-device).
  bool has_permission() const;
  void set_has_permission(bool value_arg);

  const std::string* manufacturer() const;
  void set_manufacturer(const std::string_view* value_arg);
  void set_manufacturer(std::string_view value_arg);

  const std::string* product() const;
  void set_product(const std::string_view* value_arg);
  void set_product(std::string_view value_arg);

  const std::string* serial_number() const;
  void set_serial_number(const std::string_view* value_arg);
  void set_serial_number(std::string_view value_arg);

  // Printer-class interface index (`bInterfaceClass == 0x07`). Null if no such
  // interface exists on the device.
  const int64_t* interface_number() const;
  void set_interface_number(const int64_t* value_arg);
  void set_interface_number(int64_t value_arg);

  // Bulk IN endpoint address (with direction bit).
  const int64_t* bulk_in_endpoint() const;
  void set_bulk_in_endpoint(const int64_t* value_arg);
  void set_bulk_in_endpoint(int64_t value_arg);

  // Bulk OUT endpoint address.
  const int64_t* bulk_out_endpoint() const;
  void set_bulk_out_endpoint(const int64_t* value_arg);
  void set_bulk_out_endpoint(int64_t value_arg);

  // wMaxPacketSize of the bulk-OUT endpoint. Drives auto chunk size.
  const int64_t* w_max_packet_size_out() const;
  void set_w_max_packet_size_out(const int64_t* value_arg);
  void set_w_max_packet_size_out(int64_t value_arg);

  // Windows-only. One of "WINUSB", "USBPRINT", "OTHER". Null on other platforms.
  const std::string* driver_binding() const;
  void set_driver_binding(const std::string_view* value_arg);
  void set_driver_binding(std::string_view value_arg);


 private:
  static UsbDeviceRecord FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class UsbHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t vendor_id_;
  int64_t product_id_;
  std::string path_;
  bool has_permission_;
  std::optional<std::string> manufacturer_;
  std::optional<std::string> product_;
  std::optional<std::string> serial_number_;
  std::optional<int64_t> interface_number_;
  std::optional<int64_t> bulk_in_endpoint_;
  std::optional<int64_t> bulk_out_endpoint_;
  std::optional<int64_t> w_max_packet_size_out_;
  std::optional<std::string> driver_binding_;

};


// Filter passed to [UsbHostApi.enumerate].
//
// Generated class from Pigeon that represents data sent in messages.
class UsbEnumerateFilter {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit UsbEnumerateFilter(bool include_descriptor_strings);

  // Constructs an object setting all fields.
  explicit UsbEnumerateFilter(
    const int64_t* vendor_id,
    bool include_descriptor_strings);

  // If non-null, return only devices with this vendor ID.
  const int64_t* vendor_id() const;
  void set_vendor_id(const int64_t* value_arg);
  void set_vendor_id(int64_t value_arg);

  // Reading descriptor strings is slow on Windows (~10-50ms/device).
  // Set false during hot-plug re-enumeration where latency matters.
  bool include_descriptor_strings() const;
  void set_include_descriptor_strings(bool value_arg);


 private:
  static UsbEnumerateFilter FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class UsbHostApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> vendor_id_;
  bool include_descriptor_strings_;

};


// Result of a successful [UsbHostApi.openForFfi] call. The Dart FFI layer
// takes over I/O from here.
//
// Generated class from Pigeon that represents data sent in messages.
class UsbOpenResult {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit UsbOpenResult(
    int64_t platform_handle,
    int64_t vendor_id,
    int64_t product_id,
    int64_t claimed_interface_number,
    int64_t bulk_in_endpoint,
    int64_t bulk_out_endpoint,
    int64_t w_max_packet_size_out);

  // Constructs an object setting all fields.
  explicit UsbOpenResult(
    int64_t platform_handle,
    int64_t vendor_id,
    int64_t product_id,
    const std::string* serial_number,
    int64_t claimed_interface_number,
    int64_t bulk_in_endpoint,
    int64_t bulk_out_endpoint,
    int64_t w_max_packet_size_out);

  // Android: file descriptor from `UsbDeviceConnection.getFileDescriptor()`.
  // macOS/Windows: 0 (FFI matches the device via VID+PID+serial).
  int64_t platform_handle() const;
  void set_platform_handle(int64_t value_arg);

  int64_t vendor_id() const;
  void set_vendor_id(int64_t value_arg);

  int64_t product_id() const;
  void set_product_id(int64_t value_arg);

  const std::string* serial_number() const;
  void set_serial_number(const std::string_view* value_arg);
  void set_serial_number(std::string_view value_arg);

  // Interface index that the native side has claimed.
  int64_t claimed_interface_number() const;
  void set_claimed_interface_number(int64_t value_arg);

  int64_t bulk_in_endpoint() const;
  void set_bulk_in_endpoint(int64_t value_arg);

  int64_t bulk_out_endpoint() const;
  void set_bulk_out_endpoint(int64_t value_arg);

  int64_t w_max_packet_size_out() const;
  void set_w_max_packet_size_out(int64_t value_arg);


 private:
  static UsbOpenResult FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class UsbHostApi;
  friend class PigeonInternalCodecSerializer;
  int64_t platform_handle_;
  int64_t vendor_id_;
  int64_t product_id_;
  std::optional<std::string> serial_number_;
  int64_t claimed_interface_number_;
  int64_t bulk_in_endpoint_;
  int64_t bulk_out_endpoint_;
  int64_t w_max_packet_size_out_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// USB host API — lifecycle only. Bulk I/O happens via Dart FFI directly to
// libusb; channel hops would be too expensive for the hot path.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class UsbHostApi {
 public:
  UsbHostApi(const UsbHostApi&) = delete;
  UsbHostApi& operator=(const UsbHostApi&) = delete;
  virtual ~UsbHostApi() {}
  // Quick capability probe. False on iOS and on desktops without libusb.
  virtual ErrorOr<bool> IsSupported() = 0;
  // Snapshot enumeration. Returns a complete list (no streaming).
  virtual void Enumerate(
    const UsbEnumerateFilter& filter,
    std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  // Android: `UsbManager.hasPermission(device)`. Other: always true.
  virtual ErrorOr<bool> HasPermission(const std::string& path) = 0;
  // Android: triggers system dialog; resolves when user responds.
  // Other: resolves true immediately.
  virtual void RequestPermission(
    const std::string& path,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Claims the printer-class interface on Android (fd-based libusb handoff).
  // On macOS/Windows, returns metadata so Dart FFI can call libusb_open.
  // Throws on permission denied, device busy, device disappeared, etc.
  virtual void OpenForFfi(
    const std::string& path,
    std::function<void(ErrorOr<UsbOpenResult> reply)> result) = 0;
  // Final cleanup after Dart FFI has released and closed the libusb handle.
  // Android: closes the retained `UsbDeviceConnection`. Other: no-op.
  // Must be idempotent.
  virtual void CloseAfterFfi(
    const std::string& path,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by UsbHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `UsbHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    UsbHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    UsbHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  UsbHostApi() = default;

};
}  // namespace flutter_zpl_printer
#endif  // PIGEON_USB_MESSAGES_G_H_
