// // Copyright (c) 2026 StampCommit. All rights reserved.
// // GENERATED FILE — DO NOT EDIT.
// // Regenerate with: dart run pigeon --input pigeons/usb_messages.dart
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:flutter_zpl_printer/src/platform/usb_messages.g.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is UsbDeviceRecord) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is UsbEnumerateFilter) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is UsbOpenResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return UsbDeviceRecord.decode(readValue(buffer)!);
      case 130: 
        return UsbEnumerateFilter.decode(readValue(buffer)!);
      case 131: 
        return UsbOpenResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}
