// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum ConnectionType: Int {
  case bluetooth = 0
  case wifi = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PrinterDevice {
  var name: String
  var address: String
  var type: ConnectionType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterDevice? {
    let name = pigeonVar_list[0] as! String
    let address = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! ConnectionType

    return PrinterDevice(
      name: name,
      address: address,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      address,
      type,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PrinterStatus {
  var isReadyToPrint: Bool
  var isHeadOpen: Bool
  var isHeadCold: Bool
  var isHeadTooHot: Bool
  var isPaperOut: Bool
  var isRibbonOut: Bool
  var isReceiveBufferFull: Bool
  var isPaused: Bool
  var isPartialFormatInProgress: Bool
  var labelLengthInDots: Int64
  var numberOfFormatsInReceiveBuffer: Int64
  var labelsRemainingInBatch: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterStatus? {
    let isReadyToPrint = pigeonVar_list[0] as! Bool
    let isHeadOpen = pigeonVar_list[1] as! Bool
    let isHeadCold = pigeonVar_list[2] as! Bool
    let isHeadTooHot = pigeonVar_list[3] as! Bool
    let isPaperOut = pigeonVar_list[4] as! Bool
    let isRibbonOut = pigeonVar_list[5] as! Bool
    let isReceiveBufferFull = pigeonVar_list[6] as! Bool
    let isPaused = pigeonVar_list[7] as! Bool
    let isPartialFormatInProgress = pigeonVar_list[8] as! Bool
    let labelLengthInDots = pigeonVar_list[9] as! Int64
    let numberOfFormatsInReceiveBuffer = pigeonVar_list[10] as! Int64
    let labelsRemainingInBatch = pigeonVar_list[11] as! Int64

    return PrinterStatus(
      isReadyToPrint: isReadyToPrint,
      isHeadOpen: isHeadOpen,
      isHeadCold: isHeadCold,
      isHeadTooHot: isHeadTooHot,
      isPaperOut: isPaperOut,
      isRibbonOut: isRibbonOut,
      isReceiveBufferFull: isReceiveBufferFull,
      isPaused: isPaused,
      isPartialFormatInProgress: isPartialFormatInProgress,
      labelLengthInDots: labelLengthInDots,
      numberOfFormatsInReceiveBuffer: numberOfFormatsInReceiveBuffer,
      labelsRemainingInBatch: labelsRemainingInBatch
    )
  }
  func toList() -> [Any?] {
    return [
      isReadyToPrint,
      isHeadOpen,
      isHeadCold,
      isHeadTooHot,
      isPaperOut,
      isRibbonOut,
      isReceiveBufferFull,
      isPaused,
      isPartialFormatInProgress,
      labelLengthInDots,
      numberOfFormatsInReceiveBuffer,
      labelsRemainingInBatch,
    ]
  }
}

private class PigeonGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConnectionType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PrinterDevice.fromList(self.readValue() as! [Any?])
    case 131:
      return PrinterStatus.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ConnectionType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PrinterDevice {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PrinterStatus {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonGeneratedPigeonCodecWriter(data: data)
  }
}

class PigeonGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonGeneratedPigeonCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PrinterHostApi {
  func startDiscovery(completion: @escaping (Result<Void, Error>) -> Void)
  func stopDiscovery() throws
  func connect(address: String, type: ConnectionType, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnect() throws
  func printZpl(zplPayload: String, completion: @escaping (Result<Void, Error>) -> Void)
  func getStatus(completion: @escaping (Result<PrinterStatus, Error>) -> Void)
  func getSettings(completion: @escaping (Result<[String?: String?], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PrinterHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `PrinterHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PrinterHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.startDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { _, reply in
        api.startDiscovery { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.stopDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.stopDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let addressArg = args[0] as! String
        let typeArg = args[1] as! ConnectionType
        api.connect(address: addressArg, type: typeArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        do {
          try api.disconnect()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let printZplChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.printZpl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printZplChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let zplPayloadArg = args[0] as! String
        api.printZpl(zplPayload: zplPayloadArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      printZplChannel.setMessageHandler(nil)
    }
    let getStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.getStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getStatusChannel.setMessageHandler { _, reply in
        api.getStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getStatusChannel.setMessageHandler(nil)
    }
    let getSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.getSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSettingsChannel.setMessageHandler { _, reply in
        api.getSettings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getSettingsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PrinterFlutterApiProtocol {
  func onPrinterFound(printer printerArg: PrinterDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDiscoveryCompleted(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PrinterFlutterApi: PrinterFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PigeonGeneratedPigeonCodec {
    return PigeonGeneratedPigeonCodec.shared
  }
  func onPrinterFound(printer printerArg: PrinterDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onPrinterFound\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([printerArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDiscoveryCompleted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onDiscoveryCompleted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
