// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum ConnectionType {
  bluetooth,
  wifi,
}

class PrinterDevice {
  PrinterDevice({
    required this.name,
    required this.address,
    required this.type,
  });

  String name;

  String address;

  ConnectionType type;

  Object encode() {
    return <Object?>[
      name,
      address,
      type,
    ];
  }

  static PrinterDevice decode(Object result) {
    result as List<Object?>;
    return PrinterDevice(
      name: result[0]! as String,
      address: result[1]! as String,
      type: result[2]! as ConnectionType,
    );
  }
}

class PrinterStatus {
  PrinterStatus({
    required this.isReadyToPrint,
    required this.isHeadOpen,
    required this.isHeadCold,
    required this.isHeadTooHot,
    required this.isPaperOut,
    required this.isRibbonOut,
    required this.isReceiveBufferFull,
    required this.isPaused,
    required this.isPartialFormatInProgress,
    required this.labelLengthInDots,
    required this.numberOfFormatsInReceiveBuffer,
    required this.labelsRemainingInBatch,
  });

  bool isReadyToPrint;

  bool isHeadOpen;

  bool isHeadCold;

  bool isHeadTooHot;

  bool isPaperOut;

  bool isRibbonOut;

  bool isReceiveBufferFull;

  bool isPaused;

  bool isPartialFormatInProgress;

  int labelLengthInDots;

  int numberOfFormatsInReceiveBuffer;

  int labelsRemainingInBatch;

  Object encode() {
    return <Object?>[
      isReadyToPrint,
      isHeadOpen,
      isHeadCold,
      isHeadTooHot,
      isPaperOut,
      isRibbonOut,
      isReceiveBufferFull,
      isPaused,
      isPartialFormatInProgress,
      labelLengthInDots,
      numberOfFormatsInReceiveBuffer,
      labelsRemainingInBatch,
    ];
  }

  static PrinterStatus decode(Object result) {
    result as List<Object?>;
    return PrinterStatus(
      isReadyToPrint: result[0]! as bool,
      isHeadOpen: result[1]! as bool,
      isHeadCold: result[2]! as bool,
      isHeadTooHot: result[3]! as bool,
      isPaperOut: result[4]! as bool,
      isRibbonOut: result[5]! as bool,
      isReceiveBufferFull: result[6]! as bool,
      isPaused: result[7]! as bool,
      isPartialFormatInProgress: result[8]! as bool,
      labelLengthInDots: result[9]! as int,
      numberOfFormatsInReceiveBuffer: result[10]! as int,
      labelsRemainingInBatch: result[11]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ConnectionType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PrinterDevice) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PrinterStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ConnectionType.values[value];
      case 130: 
        return PrinterDevice.decode(readValue(buffer)!);
      case 131: 
        return PrinterStatus.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PrinterHostApi {
  /// Constructor for [PrinterHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PrinterHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startDiscovery() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.startDiscovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopDiscovery() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.stopDiscovery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> connect(String address, ConnectionType type) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[address, type]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> printZpl(String zplPayload) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.printZpl$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[zplPayload]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PrinterStatus> getStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.getStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PrinterStatus?)!;
    }
  }

  Future<Map<String?, String?>> getSettings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.getSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Map<Object?, Object?>?)!.cast<String?, String?>();
    }
  }
}

abstract class PrinterFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onPrinterFound(PrinterDevice printer);

  void onDiscoveryCompleted();

  static void setUp(PrinterFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onPrinterFound$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onPrinterFound was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PrinterDevice? arg_printer = (args[0] as PrinterDevice?);
          assert(arg_printer != null,
              'Argument for dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onPrinterFound was null, expected non-null PrinterDevice.');
          try {
            api.onPrinterFound(arg_printer!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onDiscoveryCompleted$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onDiscoveryCompleted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
