// // Copyright (c) 2026 StampCommit. All rights reserved.
// // GENERATED FILE — DO NOT EDIT.
// // Regenerate with: dart run pigeon --input pigeons/usb_messages.dart
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// One USB device returned by [UsbHostApi.enumerate].
///
/// Generated class from Pigeon that represents data sent in messages.
struct UsbDeviceRecord {
  /// Vendor ID (0x0A5F for Zebra).
  var vendorId: Int64
  /// Product ID.
  var productId: Int64
  /// Platform-opaque identifier used for subsequent calls.
  /// Android: `/dev/bus/usb/001/004`. macOS: IOKit path. Windows: `\\?\USB#VID_...`.
  var path: String
  /// Android-relevant. True on macOS/Windows (permission model is per-app, not per-device).
  var hasPermission: Bool
  var manufacturer: String? = nil
  var product: String? = nil
  var serialNumber: String? = nil
  /// Printer-class interface index (`bInterfaceClass == 0x07`). Null if no such
  /// interface exists on the device.
  var interfaceNumber: Int64? = nil
  /// Bulk IN endpoint address (with direction bit).
  var bulkInEndpoint: Int64? = nil
  /// Bulk OUT endpoint address.
  var bulkOutEndpoint: Int64? = nil
  /// wMaxPacketSize of the bulk-OUT endpoint. Drives auto chunk size.
  var wMaxPacketSizeOut: Int64? = nil
  /// Windows-only. One of "WINUSB", "USBPRINT", "OTHER". Null on other platforms.
  var driverBinding: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UsbDeviceRecord? {
    let vendorId = pigeonVar_list[0] as! Int64
    let productId = pigeonVar_list[1] as! Int64
    let path = pigeonVar_list[2] as! String
    let hasPermission = pigeonVar_list[3] as! Bool
    let manufacturer: String? = nilOrValue(pigeonVar_list[4])
    let product: String? = nilOrValue(pigeonVar_list[5])
    let serialNumber: String? = nilOrValue(pigeonVar_list[6])
    let interfaceNumber: Int64? = nilOrValue(pigeonVar_list[7])
    let bulkInEndpoint: Int64? = nilOrValue(pigeonVar_list[8])
    let bulkOutEndpoint: Int64? = nilOrValue(pigeonVar_list[9])
    let wMaxPacketSizeOut: Int64? = nilOrValue(pigeonVar_list[10])
    let driverBinding: String? = nilOrValue(pigeonVar_list[11])

    return UsbDeviceRecord(
      vendorId: vendorId,
      productId: productId,
      path: path,
      hasPermission: hasPermission,
      manufacturer: manufacturer,
      product: product,
      serialNumber: serialNumber,
      interfaceNumber: interfaceNumber,
      bulkInEndpoint: bulkInEndpoint,
      bulkOutEndpoint: bulkOutEndpoint,
      wMaxPacketSizeOut: wMaxPacketSizeOut,
      driverBinding: driverBinding
    )
  }
  func toList() -> [Any?] {
    return [
      vendorId,
      productId,
      path,
      hasPermission,
      manufacturer,
      product,
      serialNumber,
      interfaceNumber,
      bulkInEndpoint,
      bulkOutEndpoint,
      wMaxPacketSizeOut,
      driverBinding,
    ]
  }
}

/// Filter passed to [UsbHostApi.enumerate].
///
/// Generated class from Pigeon that represents data sent in messages.
struct UsbEnumerateFilter {
  /// If non-null, return only devices with this vendor ID.
  var vendorId: Int64? = nil
  /// Reading descriptor strings is slow on Windows (~10-50ms/device).
  /// Set false during hot-plug re-enumeration where latency matters.
  var includeDescriptorStrings: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UsbEnumerateFilter? {
    let vendorId: Int64? = nilOrValue(pigeonVar_list[0])
    let includeDescriptorStrings = pigeonVar_list[1] as! Bool

    return UsbEnumerateFilter(
      vendorId: vendorId,
      includeDescriptorStrings: includeDescriptorStrings
    )
  }
  func toList() -> [Any?] {
    return [
      vendorId,
      includeDescriptorStrings,
    ]
  }
}

/// Result of a successful [UsbHostApi.openForFfi] call. The Dart FFI layer
/// takes over I/O from here.
///
/// Generated class from Pigeon that represents data sent in messages.
struct UsbOpenResult {
  /// Android: file descriptor from `UsbDeviceConnection.getFileDescriptor()`.
  /// macOS/Windows: 0 (FFI matches the device via VID+PID+serial).
  var platformHandle: Int64
  var vendorId: Int64
  var productId: Int64
  var serialNumber: String? = nil
  /// Interface index that the native side has claimed.
  var claimedInterfaceNumber: Int64
  var bulkInEndpoint: Int64
  var bulkOutEndpoint: Int64
  var wMaxPacketSizeOut: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UsbOpenResult? {
    let platformHandle = pigeonVar_list[0] as! Int64
    let vendorId = pigeonVar_list[1] as! Int64
    let productId = pigeonVar_list[2] as! Int64
    let serialNumber: String? = nilOrValue(pigeonVar_list[3])
    let claimedInterfaceNumber = pigeonVar_list[4] as! Int64
    let bulkInEndpoint = pigeonVar_list[5] as! Int64
    let bulkOutEndpoint = pigeonVar_list[6] as! Int64
    let wMaxPacketSizeOut = pigeonVar_list[7] as! Int64

    return UsbOpenResult(
      platformHandle: platformHandle,
      vendorId: vendorId,
      productId: productId,
      serialNumber: serialNumber,
      claimedInterfaceNumber: claimedInterfaceNumber,
      bulkInEndpoint: bulkInEndpoint,
      bulkOutEndpoint: bulkOutEndpoint,
      wMaxPacketSizeOut: wMaxPacketSizeOut
    )
  }
  func toList() -> [Any?] {
    return [
      platformHandle,
      vendorId,
      productId,
      serialNumber,
      claimedInterfaceNumber,
      bulkInEndpoint,
      bulkOutEndpoint,
      wMaxPacketSizeOut,
    ]
  }
}

private class UsbMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return UsbDeviceRecord.fromList(self.readValue() as! [Any?])
    case 130:
      return UsbEnumerateFilter.fromList(self.readValue() as! [Any?])
    case 131:
      return UsbOpenResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class UsbMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? UsbDeviceRecord {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? UsbEnumerateFilter {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? UsbOpenResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UsbMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UsbMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UsbMessagesPigeonCodecWriter(data: data)
  }
}

class UsbMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = UsbMessagesPigeonCodec(readerWriter: UsbMessagesPigeonCodecReaderWriter())
}


/// USB host API — lifecycle only. Bulk I/O happens via Dart FFI directly to
/// libusb; channel hops would be too expensive for the hot path.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UsbHostApi {
  /// Quick capability probe. False on iOS and on desktops without libusb.
  func isSupported() throws -> Bool
  /// Snapshot enumeration. Returns a complete list (no streaming).
  func enumerate(filter: UsbEnumerateFilter, completion: @escaping (Result<[UsbDeviceRecord], Error>) -> Void)
  /// Android: `UsbManager.hasPermission(device)`. Other: always true.
  func hasPermission(path: String) throws -> Bool
  /// Android: triggers system dialog; resolves when user responds.
  /// Other: resolves true immediately.
  func requestPermission(path: String, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Claims the printer-class interface on Android (fd-based libusb handoff).
  /// On macOS/Windows, returns metadata so Dart FFI can call libusb_open.
  /// Throws on permission denied, device busy, device disappeared, etc.
  func openForFfi(path: String, completion: @escaping (Result<UsbOpenResult, Error>) -> Void)
  /// Final cleanup after Dart FFI has released and closed the libusb handle.
  /// Android: closes the retained `UsbDeviceConnection`. Other: no-op.
  /// Must be idempotent.
  func closeAfterFfi(path: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UsbHostApiSetup {
  static var codec: FlutterStandardMessageCodec { UsbMessagesPigeonCodec.shared }
  /// Sets up an instance of `UsbHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UsbHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Quick capability probe. False on iOS and on desktops without libusb.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Snapshot enumeration. Returns a complete list (no streaming).
    let enumerateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.enumerate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enumerateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filterArg = args[0] as! UsbEnumerateFilter
        api.enumerate(filter: filterArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enumerateChannel.setMessageHandler(nil)
    }
    /// Android: `UsbManager.hasPermission(device)`. Other: always true.
    let hasPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.hasPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        do {
          let result = try api.hasPermission(path: pathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasPermissionChannel.setMessageHandler(nil)
    }
    /// Android: triggers system dialog; resolves when user responds.
    /// Other: resolves true immediately.
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.requestPermission(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    /// Claims the printer-class interface on Android (fd-based libusb handoff).
    /// On macOS/Windows, returns metadata so Dart FFI can call libusb_open.
    /// Throws on permission denied, device busy, device disappeared, etc.
    let openForFfiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.openForFfi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openForFfiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.openForFfi(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openForFfiChannel.setMessageHandler(nil)
    }
    /// Final cleanup after Dart FFI has released and closed the libusb handle.
    /// Android: closes the retained `UsbDeviceConnection`. Other: no-op.
    /// Must be idempotent.
    let closeAfterFfiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.closeAfterFfi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeAfterFfiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.closeAfterFfi(path: pathArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeAfterFfiChannel.setMessageHandler(nil)
    }
  }
}
