// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_zpl_printer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ConnectionType(val raw: Int) {
  BLUETOOTH(0),
  WIFI(1);

  companion object {
    fun ofRaw(raw: Int): ConnectionType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PrinterDevice (
  val name: String,
  val address: String,
  val type: ConnectionType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PrinterDevice {
      val name = pigeonVar_list[0] as String
      val address = pigeonVar_list[1] as String
      val type = pigeonVar_list[2] as ConnectionType
      return PrinterDevice(name, address, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      address,
      type,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PrinterStatus (
  val isReadyToPrint: Boolean,
  val isHeadOpen: Boolean,
  val isHeadCold: Boolean,
  val isHeadTooHot: Boolean,
  val isPaperOut: Boolean,
  val isRibbonOut: Boolean,
  val isReceiveBufferFull: Boolean,
  val isPaused: Boolean,
  val isPartialFormatInProgress: Boolean,
  val labelLengthInDots: Long,
  val numberOfFormatsInReceiveBuffer: Long,
  val labelsRemainingInBatch: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PrinterStatus {
      val isReadyToPrint = pigeonVar_list[0] as Boolean
      val isHeadOpen = pigeonVar_list[1] as Boolean
      val isHeadCold = pigeonVar_list[2] as Boolean
      val isHeadTooHot = pigeonVar_list[3] as Boolean
      val isPaperOut = pigeonVar_list[4] as Boolean
      val isRibbonOut = pigeonVar_list[5] as Boolean
      val isReceiveBufferFull = pigeonVar_list[6] as Boolean
      val isPaused = pigeonVar_list[7] as Boolean
      val isPartialFormatInProgress = pigeonVar_list[8] as Boolean
      val labelLengthInDots = pigeonVar_list[9] as Long
      val numberOfFormatsInReceiveBuffer = pigeonVar_list[10] as Long
      val labelsRemainingInBatch = pigeonVar_list[11] as Long
      return PrinterStatus(isReadyToPrint, isHeadOpen, isHeadCold, isHeadTooHot, isPaperOut, isRibbonOut, isReceiveBufferFull, isPaused, isPartialFormatInProgress, labelLengthInDots, numberOfFormatsInReceiveBuffer, labelsRemainingInBatch)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isReadyToPrint,
      isHeadOpen,
      isHeadCold,
      isHeadTooHot,
      isPaperOut,
      isRibbonOut,
      isReceiveBufferFull,
      isPaused,
      isPartialFormatInProgress,
      labelLengthInDots,
      numberOfFormatsInReceiveBuffer,
      labelsRemainingInBatch,
    )
  }
}
private open class PigeonGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConnectionType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PrinterDevice.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PrinterStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConnectionType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PrinterDevice -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PrinterStatus -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PrinterHostApi {
  fun startDiscovery(callback: (Result<Unit>) -> Unit)
  fun stopDiscovery()
  fun connect(address: String, type: ConnectionType, callback: (Result<Unit>) -> Unit)
  fun disconnect()
  fun printZpl(zplPayload: String, callback: (Result<Unit>) -> Unit)
  fun getStatus(callback: (Result<PrinterStatus>) -> Unit)
  fun getSettings(callback: (Result<Map<String?, String?>>) -> Unit)

  companion object {
    /** The codec used by PrinterHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
    /** Sets up an instance of `PrinterHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PrinterHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.startDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startDiscovery{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.stopDiscovery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopDiscovery()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val addressArg = args[0] as String
            val typeArg = args[1] as ConnectionType
            api.connect(addressArg, typeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disconnect()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.printZpl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val zplPayloadArg = args[0] as String
            api.printZpl(zplPayloadArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatus{ result: Result<PrinterStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.PrinterHostApi.getSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getSettings{ result: Result<Map<String?, String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PrinterFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PrinterFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
  }
  fun onPrinterFound(printerArg: PrinterDevice, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onPrinterFound$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(printerArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDiscoveryCompleted(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_zpl_printer.PrinterFlutterApi.onDiscoveryCompleted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
