// // Copyright (c) 2026 StampCommit. All rights reserved.
// // GENERATED FILE — DO NOT EDIT.
// // Regenerate with: dart run pigeon --input pigeons/usb_messages.dart
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_zpl_printer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * One USB device returned by [UsbHostApi.enumerate].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UsbDeviceRecord (
  /** Vendor ID (0x0A5F for Zebra). */
  val vendorId: Long,
  /** Product ID. */
  val productId: Long,
  /**
   * Platform-opaque identifier used for subsequent calls.
   * Android: `/dev/bus/usb/001/004`. macOS: IOKit path. Windows: `\\?\USB#VID_...`.
   */
  val path: String,
  /** Android-relevant. True on macOS/Windows (permission model is per-app, not per-device). */
  val hasPermission: Boolean,
  val manufacturer: String? = null,
  val product: String? = null,
  val serialNumber: String? = null,
  /**
   * Printer-class interface index (`bInterfaceClass == 0x07`). Null if no such
   * interface exists on the device.
   */
  val interfaceNumber: Long? = null,
  /** Bulk IN endpoint address (with direction bit). */
  val bulkInEndpoint: Long? = null,
  /** Bulk OUT endpoint address. */
  val bulkOutEndpoint: Long? = null,
  /** wMaxPacketSize of the bulk-OUT endpoint. Drives auto chunk size. */
  val wMaxPacketSizeOut: Long? = null,
  /** Windows-only. One of "WINUSB", "USBPRINT", "OTHER". Null on other platforms. */
  val driverBinding: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UsbDeviceRecord {
      val vendorId = pigeonVar_list[0] as Long
      val productId = pigeonVar_list[1] as Long
      val path = pigeonVar_list[2] as String
      val hasPermission = pigeonVar_list[3] as Boolean
      val manufacturer = pigeonVar_list[4] as String?
      val product = pigeonVar_list[5] as String?
      val serialNumber = pigeonVar_list[6] as String?
      val interfaceNumber = pigeonVar_list[7] as Long?
      val bulkInEndpoint = pigeonVar_list[8] as Long?
      val bulkOutEndpoint = pigeonVar_list[9] as Long?
      val wMaxPacketSizeOut = pigeonVar_list[10] as Long?
      val driverBinding = pigeonVar_list[11] as String?
      return UsbDeviceRecord(vendorId, productId, path, hasPermission, manufacturer, product, serialNumber, interfaceNumber, bulkInEndpoint, bulkOutEndpoint, wMaxPacketSizeOut, driverBinding)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vendorId,
      productId,
      path,
      hasPermission,
      manufacturer,
      product,
      serialNumber,
      interfaceNumber,
      bulkInEndpoint,
      bulkOutEndpoint,
      wMaxPacketSizeOut,
      driverBinding,
    )
  }
}

/**
 * Filter passed to [UsbHostApi.enumerate].
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UsbEnumerateFilter (
  /** If non-null, return only devices with this vendor ID. */
  val vendorId: Long? = null,
  /**
   * Reading descriptor strings is slow on Windows (~10-50ms/device).
   * Set false during hot-plug re-enumeration where latency matters.
   */
  val includeDescriptorStrings: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UsbEnumerateFilter {
      val vendorId = pigeonVar_list[0] as Long?
      val includeDescriptorStrings = pigeonVar_list[1] as Boolean
      return UsbEnumerateFilter(vendorId, includeDescriptorStrings)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      vendorId,
      includeDescriptorStrings,
    )
  }
}

/**
 * Result of a successful [UsbHostApi.openForFfi] call. The Dart FFI layer
 * takes over I/O from here.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UsbOpenResult (
  /**
   * Android: file descriptor from `UsbDeviceConnection.getFileDescriptor()`.
   * macOS/Windows: 0 (FFI matches the device via VID+PID+serial).
   */
  val platformHandle: Long,
  val vendorId: Long,
  val productId: Long,
  val serialNumber: String? = null,
  /** Interface index that the native side has claimed. */
  val claimedInterfaceNumber: Long,
  val bulkInEndpoint: Long,
  val bulkOutEndpoint: Long,
  val wMaxPacketSizeOut: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UsbOpenResult {
      val platformHandle = pigeonVar_list[0] as Long
      val vendorId = pigeonVar_list[1] as Long
      val productId = pigeonVar_list[2] as Long
      val serialNumber = pigeonVar_list[3] as String?
      val claimedInterfaceNumber = pigeonVar_list[4] as Long
      val bulkInEndpoint = pigeonVar_list[5] as Long
      val bulkOutEndpoint = pigeonVar_list[6] as Long
      val wMaxPacketSizeOut = pigeonVar_list[7] as Long
      return UsbOpenResult(platformHandle, vendorId, productId, serialNumber, claimedInterfaceNumber, bulkInEndpoint, bulkOutEndpoint, wMaxPacketSizeOut)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platformHandle,
      vendorId,
      productId,
      serialNumber,
      claimedInterfaceNumber,
      bulkInEndpoint,
      bulkOutEndpoint,
      wMaxPacketSizeOut,
    )
  }
}
private open class UsbMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UsbDeviceRecord.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UsbEnumerateFilter.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UsbOpenResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is UsbDeviceRecord -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is UsbEnumerateFilter -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is UsbOpenResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * USB host API — lifecycle only. Bulk I/O happens via Dart FFI directly to
 * libusb; channel hops would be too expensive for the hot path.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface UsbHostApi {
  /** Quick capability probe. False on iOS and on desktops without libusb. */
  fun isSupported(): Boolean
  /** Snapshot enumeration. Returns a complete list (no streaming). */
  fun enumerate(filter: UsbEnumerateFilter, callback: (Result<List<UsbDeviceRecord>>) -> Unit)
  /** Android: `UsbManager.hasPermission(device)`. Other: always true. */
  fun hasPermission(path: String): Boolean
  /**
   * Android: triggers system dialog; resolves when user responds.
   * Other: resolves true immediately.
   */
  fun requestPermission(path: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Claims the printer-class interface on Android (fd-based libusb handoff).
   * On macOS/Windows, returns metadata so Dart FFI can call libusb_open.
   * Throws on permission denied, device busy, device disappeared, etc.
   */
  fun openForFfi(path: String, callback: (Result<UsbOpenResult>) -> Unit)
  /**
   * Final cleanup after Dart FFI has released and closed the libusb handle.
   * Android: closes the retained `UsbDeviceConnection`. Other: no-op.
   * Must be idempotent.
   */
  fun closeAfterFfi(path: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by UsbHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      UsbMessagesPigeonCodec()
    }
    /** Sets up an instance of `UsbHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UsbHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.enumerate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as UsbEnumerateFilter
            api.enumerate(filterArg) { result: Result<List<UsbDeviceRecord>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.hasPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.hasPermission(pathArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.requestPermission(pathArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.openForFfi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.openForFfi(pathArg) { result: Result<UsbOpenResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.closeAfterFfi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.closeAfterFfi(pathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
