// ignore_for_file: type=lint, unused_field, unused_element, non_constant_identifier_names
// GENERATED by ffigen — do not edit. Source: libusb-1.0.29

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<ffi.Pointer<ffi.Char>>>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> tzname;

@ffi.Native<ffi.Int>()
external int getdate_err;

@ffi.Native<ffi.Long>()
external int timezone;

@ffi.Native<ffi.Int>()
external int daylight;

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<libusb_context>>)>()
external int libusb_init(ffi.Pointer<ffi.Pointer<libusb_context>> ctx);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Pointer<libusb_context>>,
    ffi.Pointer<libusb_init_option>,
    ffi.Int,
  )
>()
external int libusb_init_context(
  ffi.Pointer<ffi.Pointer<libusb_context>> ctx,
  ffi.Pointer<libusb_init_option> options,
  int num_options,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<libusb_context>)>()
external void libusb_exit(ffi.Pointer<libusb_context> ctx);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> libusb_error_name(int error_code);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> libusb_strerror(int errcode);

@ffi.Native<
  ssize_t Function(
    ffi.Pointer<libusb_context>,
    ffi.Pointer<ffi.Pointer<ffi.Pointer<libusb_device>>>,
  )
>()
external int libusb_get_device_list(
  ffi.Pointer<libusb_context> ctx,
  ffi.Pointer<ffi.Pointer<ffi.Pointer<libusb_device>>> list,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Pointer<libusb_device>>, ffi.Int)
>()
external void libusb_free_device_list(
  ffi.Pointer<ffi.Pointer<libusb_device>> list,
  int unref_devices,
);

@ffi.Native<ffi.Pointer<libusb_device> Function(ffi.Pointer<libusb_device>)>()
external ffi.Pointer<libusb_device> libusb_ref_device(
  ffi.Pointer<libusb_device> dev,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<libusb_device>)>()
external void libusb_unref_device(ffi.Pointer<libusb_device> dev);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device>,
    ffi.Pointer<libusb_device_descriptor>,
  )
>()
external int libusb_get_device_descriptor(
  ffi.Pointer<libusb_device> dev,
  ffi.Pointer<libusb_device_descriptor> desc,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device>,
    ffi.Pointer<ffi.Pointer<libusb_config_descriptor>>,
  )
>()
external int libusb_get_active_config_descriptor(
  ffi.Pointer<libusb_device> dev,
  ffi.Pointer<ffi.Pointer<libusb_config_descriptor>> config,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device>,
    ffi.Uint8,
    ffi.Pointer<ffi.Pointer<libusb_config_descriptor>>,
  )
>()
external int libusb_get_config_descriptor(
  ffi.Pointer<libusb_device> dev,
  int config_index,
  ffi.Pointer<ffi.Pointer<libusb_config_descriptor>> config,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<libusb_config_descriptor>)>()
external void libusb_free_config_descriptor(
  ffi.Pointer<libusb_config_descriptor> config,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<libusb_device>)>()
external int libusb_get_bus_number(ffi.Pointer<libusb_device> dev);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<libusb_device>)>()
external int libusb_get_device_address(ffi.Pointer<libusb_device> dev);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_context>,
    ffi.IntPtr,
    ffi.Pointer<ffi.Pointer<libusb_device_handle>>,
  )
>()
external int libusb_wrap_sys_device(
  ffi.Pointer<libusb_context> ctx,
  int sys_dev,
  ffi.Pointer<ffi.Pointer<libusb_device_handle>> dev_handle,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device>,
    ffi.Pointer<ffi.Pointer<libusb_device_handle>>,
  )
>()
external int libusb_open(
  ffi.Pointer<libusb_device> dev,
  ffi.Pointer<ffi.Pointer<libusb_device_handle>> dev_handle,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<libusb_device_handle>)>()
external void libusb_close(ffi.Pointer<libusb_device_handle> dev_handle);

@ffi.Native<ffi.Int Function(ffi.Pointer<libusb_device_handle>, ffi.Int)>()
external int libusb_claim_interface(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int interface_number,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<libusb_device_handle>, ffi.Int)>()
external int libusb_release_interface(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int interface_number,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<libusb_device_handle>, ffi.UnsignedChar)
>()
external int libusb_clear_halt(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int endpoint,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<libusb_device_handle>)>()
external int libusb_reset_device(ffi.Pointer<libusb_device_handle> dev_handle);

@ffi.Native<ffi.Int Function(ffi.Pointer<libusb_device_handle>, ffi.Int)>()
external int libusb_kernel_driver_active(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int interface_number,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<libusb_device_handle>, ffi.Int)>()
external int libusb_detach_kernel_driver(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int interface_number,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<libusb_device_handle>, ffi.Int)>()
external int libusb_set_auto_detach_kernel_driver(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int enable,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device_handle>,
    ffi.Uint8,
    ffi.Uint8,
    ffi.Uint16,
    ffi.Uint16,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Uint16,
    ffi.UnsignedInt,
  )
>()
external int libusb_control_transfer(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int bmRequestType,
  int bRequest,
  int wValue,
  int wIndex,
  ffi.Pointer<ffi.UnsignedChar> data,
  int wLength,
  int timeout,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device_handle>,
    ffi.UnsignedChar,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Int,
    ffi.Pointer<ffi.Int>,
    ffi.UnsignedInt,
  )
>()
external int libusb_bulk_transfer(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int endpoint,
  ffi.Pointer<ffi.UnsignedChar> data,
  int length,
  ffi.Pointer<ffi.Int> transferred,
  int timeout,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<libusb_device_handle>,
    ffi.Uint8,
    ffi.Pointer<ffi.UnsignedChar>,
    ffi.Int,
  )
>()
external int libusb_get_string_descriptor_ascii(
  ffi.Pointer<libusb_device_handle> dev_handle,
  int desc_index,
  ffi.Pointer<ffi.UnsignedChar> data,
  int length,
);

final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;
}

/// Device and/or Interface Class codes
enum libusb_class_code {
  /// In the context of a libusb_device_descriptor "device descriptor", this
  /// bDeviceClass value indicates that each interface specifies its own class
  /// information and all interfaces operate independently.
  LIBUSB_CLASS_PER_INTERFACE(0),

  /// Audio class
  LIBUSB_CLASS_AUDIO(1),

  /// Communications class
  LIBUSB_CLASS_COMM(2),

  /// Human Interface Device class
  LIBUSB_CLASS_HID(3),

  /// Physical
  LIBUSB_CLASS_PHYSICAL(5),

  /// Image class
  LIBUSB_CLASS_IMAGE(6),

  /// Printer class
  LIBUSB_CLASS_PRINTER(7),

  /// Mass storage class
  LIBUSB_CLASS_MASS_STORAGE(8),

  /// Hub class
  LIBUSB_CLASS_HUB(9),

  /// Data class
  LIBUSB_CLASS_DATA(10),

  /// Smart Card
  LIBUSB_CLASS_SMART_CARD(11),

  /// Content Security
  LIBUSB_CLASS_CONTENT_SECURITY(13),

  /// Video
  LIBUSB_CLASS_VIDEO(14),

  /// Personal Healthcare
  LIBUSB_CLASS_PERSONAL_HEALTHCARE(15),

  /// Diagnostic Device
  LIBUSB_CLASS_DIAGNOSTIC_DEVICE(220),

  /// Wireless class
  LIBUSB_CLASS_WIRELESS(224),

  /// Miscellaneous class
  LIBUSB_CLASS_MISCELLANEOUS(239),

  /// Application class
  LIBUSB_CLASS_APPLICATION(254),

  /// Class is vendor-specific
  LIBUSB_CLASS_VENDOR_SPEC(255);

  static const LIBUSB_CLASS_PTP = LIBUSB_CLASS_IMAGE;

  final int value;
  const libusb_class_code(this.value);

  static libusb_class_code fromValue(int value) => switch (value) {
    0 => LIBUSB_CLASS_PER_INTERFACE,
    1 => LIBUSB_CLASS_AUDIO,
    2 => LIBUSB_CLASS_COMM,
    3 => LIBUSB_CLASS_HID,
    5 => LIBUSB_CLASS_PHYSICAL,
    6 => LIBUSB_CLASS_IMAGE,
    7 => LIBUSB_CLASS_PRINTER,
    8 => LIBUSB_CLASS_MASS_STORAGE,
    9 => LIBUSB_CLASS_HUB,
    10 => LIBUSB_CLASS_DATA,
    11 => LIBUSB_CLASS_SMART_CARD,
    13 => LIBUSB_CLASS_CONTENT_SECURITY,
    14 => LIBUSB_CLASS_VIDEO,
    15 => LIBUSB_CLASS_PERSONAL_HEALTHCARE,
    220 => LIBUSB_CLASS_DIAGNOSTIC_DEVICE,
    224 => LIBUSB_CLASS_WIRELESS,
    239 => LIBUSB_CLASS_MISCELLANEOUS,
    254 => LIBUSB_CLASS_APPLICATION,
    255 => LIBUSB_CLASS_VENDOR_SPEC,
    _ => throw ArgumentError("Unknown value for libusb_class_code: $value"),
  };

  @override
  String toString() {
    if (this == LIBUSB_CLASS_IMAGE)
      return "libusb_class_code.LIBUSB_CLASS_IMAGE, libusb_class_code.LIBUSB_CLASS_PTP";
    return super.toString();
  }
}

/// Descriptor types as defined by the USB specification.
enum libusb_descriptor_type {
  /// Device descriptor. See libusb_device_descriptor.
  LIBUSB_DT_DEVICE(1),

  /// Configuration descriptor. See libusb_config_descriptor.
  LIBUSB_DT_CONFIG(2),

  /// String descriptor
  LIBUSB_DT_STRING(3),

  /// Interface descriptor. See libusb_interface_descriptor.
  LIBUSB_DT_INTERFACE(4),

  /// Endpoint descriptor. See libusb_endpoint_descriptor.
  LIBUSB_DT_ENDPOINT(5),

  /// Interface Association Descriptor. See
  /// libusb_interface_association_descriptor
  LIBUSB_DT_INTERFACE_ASSOCIATION(11),

  /// BOS descriptor
  LIBUSB_DT_BOS(15),

  /// Device Capability descriptor
  LIBUSB_DT_DEVICE_CAPABILITY(16),

  /// HID descriptor
  LIBUSB_DT_HID(33),

  /// HID report descriptor
  LIBUSB_DT_REPORT(34),

  /// Physical descriptor
  LIBUSB_DT_PHYSICAL(35),

  /// Hub descriptor
  LIBUSB_DT_HUB(41),

  /// SuperSpeed Hub descriptor
  LIBUSB_DT_SUPERSPEED_HUB(42),

  /// SuperSpeed Endpoint Companion descriptor
  LIBUSB_DT_SS_ENDPOINT_COMPANION(48);

  final int value;
  const libusb_descriptor_type(this.value);

  static libusb_descriptor_type fromValue(int value) => switch (value) {
    1 => LIBUSB_DT_DEVICE,
    2 => LIBUSB_DT_CONFIG,
    3 => LIBUSB_DT_STRING,
    4 => LIBUSB_DT_INTERFACE,
    5 => LIBUSB_DT_ENDPOINT,
    11 => LIBUSB_DT_INTERFACE_ASSOCIATION,
    15 => LIBUSB_DT_BOS,
    16 => LIBUSB_DT_DEVICE_CAPABILITY,
    33 => LIBUSB_DT_HID,
    34 => LIBUSB_DT_REPORT,
    35 => LIBUSB_DT_PHYSICAL,
    41 => LIBUSB_DT_HUB,
    42 => LIBUSB_DT_SUPERSPEED_HUB,
    48 => LIBUSB_DT_SS_ENDPOINT_COMPANION,
    _ => throw ArgumentError(
      "Unknown value for libusb_descriptor_type: $value",
    ),
  };
}

/// Endpoint direction. Values for bit 7 of the
/// libusb_endpoint_descriptor::bEndpointAddress "endpoint address" scheme.
enum libusb_endpoint_direction {
  /// Out: host-to-device
  LIBUSB_ENDPOINT_OUT(0),

  /// In: device-to-host
  LIBUSB_ENDPOINT_IN(128);

  final int value;
  const libusb_endpoint_direction(this.value);

  static libusb_endpoint_direction fromValue(int value) => switch (value) {
    0 => LIBUSB_ENDPOINT_OUT,
    128 => LIBUSB_ENDPOINT_IN,
    _ => throw ArgumentError(
      "Unknown value for libusb_endpoint_direction: $value",
    ),
  };
}

/// Standard requests, as defined in table 9-5 of the USB 3.0 specifications
enum libusb_standard_request {
  /// Request status of the specific recipient
  LIBUSB_REQUEST_GET_STATUS(0),

  /// Clear or disable a specific feature
  LIBUSB_REQUEST_CLEAR_FEATURE(1),

  /// Set or enable a specific feature
  LIBUSB_REQUEST_SET_FEATURE(3),

  /// Set device address for all future accesses
  LIBUSB_REQUEST_SET_ADDRESS(5),

  /// Get the specified descriptor
  LIBUSB_REQUEST_GET_DESCRIPTOR(6),

  /// Used to update existing descriptors or add new descriptors
  LIBUSB_REQUEST_SET_DESCRIPTOR(7),

  /// Get the current device configuration value
  LIBUSB_REQUEST_GET_CONFIGURATION(8),

  /// Set device configuration
  LIBUSB_REQUEST_SET_CONFIGURATION(9),

  /// Return the selected alternate setting for the specified interface
  LIBUSB_REQUEST_GET_INTERFACE(10),

  /// Select an alternate interface for the specified interface
  LIBUSB_REQUEST_SET_INTERFACE(11),

  /// Set then report an endpoint's synchronization frame
  LIBUSB_REQUEST_SYNCH_FRAME(12),

  /// Sets both the U1 and U2 Exit Latency
  LIBUSB_REQUEST_SET_SEL(48),

  /// Delay from the time a host transmits a packet to the time it is received
  /// by the device.
  LIBUSB_SET_ISOCH_DELAY(49);

  final int value;
  const libusb_standard_request(this.value);

  static libusb_standard_request fromValue(int value) => switch (value) {
    0 => LIBUSB_REQUEST_GET_STATUS,
    1 => LIBUSB_REQUEST_CLEAR_FEATURE,
    3 => LIBUSB_REQUEST_SET_FEATURE,
    5 => LIBUSB_REQUEST_SET_ADDRESS,
    6 => LIBUSB_REQUEST_GET_DESCRIPTOR,
    7 => LIBUSB_REQUEST_SET_DESCRIPTOR,
    8 => LIBUSB_REQUEST_GET_CONFIGURATION,
    9 => LIBUSB_REQUEST_SET_CONFIGURATION,
    10 => LIBUSB_REQUEST_GET_INTERFACE,
    11 => LIBUSB_REQUEST_SET_INTERFACE,
    12 => LIBUSB_REQUEST_SYNCH_FRAME,
    48 => LIBUSB_REQUEST_SET_SEL,
    49 => LIBUSB_SET_ISOCH_DELAY,
    _ => throw ArgumentError(
      "Unknown value for libusb_standard_request: $value",
    ),
  };
}

/// Request type bits of the libusb_control_setup::bmRequestType "bmRequestType"
/// field in control transfers.
enum libusb_request_type {
  /// Standard
  LIBUSB_REQUEST_TYPE_STANDARD(0),

  /// Class
  LIBUSB_REQUEST_TYPE_CLASS(32),

  /// Vendor
  LIBUSB_REQUEST_TYPE_VENDOR(64),

  /// Reserved
  LIBUSB_REQUEST_TYPE_RESERVED(96);

  final int value;
  const libusb_request_type(this.value);

  static libusb_request_type fromValue(int value) => switch (value) {
    0 => LIBUSB_REQUEST_TYPE_STANDARD,
    32 => LIBUSB_REQUEST_TYPE_CLASS,
    64 => LIBUSB_REQUEST_TYPE_VENDOR,
    96 => LIBUSB_REQUEST_TYPE_RESERVED,
    _ => throw ArgumentError("Unknown value for libusb_request_type: $value"),
  };
}

/// Recipient bits of the libusb_control_setup::bmRequestType "bmRequestType"
/// field in control transfers. Values 4 through 31 are reserved.
enum libusb_request_recipient {
  /// Device
  LIBUSB_RECIPIENT_DEVICE(0),

  /// Interface
  LIBUSB_RECIPIENT_INTERFACE(1),

  /// Endpoint
  LIBUSB_RECIPIENT_ENDPOINT(2),

  /// Other
  LIBUSB_RECIPIENT_OTHER(3);

  final int value;
  const libusb_request_recipient(this.value);

  static libusb_request_recipient fromValue(int value) => switch (value) {
    0 => LIBUSB_RECIPIENT_DEVICE,
    1 => LIBUSB_RECIPIENT_INTERFACE,
    2 => LIBUSB_RECIPIENT_ENDPOINT,
    3 => LIBUSB_RECIPIENT_OTHER,
    _ => throw ArgumentError(
      "Unknown value for libusb_request_recipient: $value",
    ),
  };
}

/// A structure representing the standard USB device descriptor. This descriptor
/// is documented in section 9.6.1 of the USB 3.0 specification. All
/// multiple-byte fields are represented in host-endian format.
final class libusb_device_descriptor extends ffi.Struct {
  /// Size of this descriptor (in bytes)
  @ffi.Uint8()
  external int bLength;

  /// Descriptor type. Will have value libusb_descriptor_type::LIBUSB_DT_DEVICE
  /// LIBUSB_DT_DEVICE in this context.
  @ffi.Uint8()
  external int bDescriptorType;

  /// USB specification release number in binary-coded decimal. A value of
  /// 0x0200 indicates USB 2.0, 0x0110 indicates USB 1.1, etc.
  @ffi.Uint16()
  external int bcdUSB;

  /// USB-IF class code for the device. See libusb_class_code.
  @ffi.Uint8()
  external int bDeviceClass;

  /// USB-IF subclass code for the device, qualified by the bDeviceClass value
  @ffi.Uint8()
  external int bDeviceSubClass;

  /// USB-IF protocol code for the device, qualified by the bDeviceClass and
  /// bDeviceSubClass values
  @ffi.Uint8()
  external int bDeviceProtocol;

  /// Maximum packet size for endpoint 0
  @ffi.Uint8()
  external int bMaxPacketSize0;

  /// USB-IF vendor ID
  @ffi.Uint16()
  external int idVendor;

  /// USB-IF product ID
  @ffi.Uint16()
  external int idProduct;

  /// Device release number in binary-coded decimal
  @ffi.Uint16()
  external int bcdDevice;

  /// Index of string descriptor describing manufacturer
  @ffi.Uint8()
  external int iManufacturer;

  /// Index of string descriptor describing product
  @ffi.Uint8()
  external int iProduct;

  /// Index of string descriptor containing device serial number
  @ffi.Uint8()
  external int iSerialNumber;

  /// Number of possible configurations
  @ffi.Uint8()
  external int bNumConfigurations;
}

/// A structure representing the standard USB endpoint descriptor. This
/// descriptor is documented in section 9.6.6 of the USB 3.0 specification. All
/// multiple-byte fields are represented in host-endian format.
final class libusb_endpoint_descriptor extends ffi.Struct {
  /// Size of this descriptor (in bytes)
  @ffi.Uint8()
  external int bLength;

  /// Descriptor type. Will have value
  /// libusb_descriptor_type::LIBUSB_DT_ENDPOINT LIBUSB_DT_ENDPOINT in this
  /// context.
  @ffi.Uint8()
  external int bDescriptorType;

  /// The address of the endpoint described by this descriptor. Bits 0:3 are the
  /// endpoint number. Bits 4:6 are reserved. Bit 7 indicates direction, see
  /// libusb_endpoint_direction.
  @ffi.Uint8()
  external int bEndpointAddress;

  /// Attributes which apply to the endpoint when it is configured using the
  /// bConfigurationValue. Bits 0:1 determine the transfer type and correspond
  /// to libusb_endpoint_transfer_type. Bits 2:3 are only used for isochronous
  /// endpoints and correspond to libusb_iso_sync_type. Bits 4:5 are also only
  /// used for isochronous endpoints and correspond to libusb_iso_usage_type.
  /// Bits 6:7 are reserved.
  @ffi.Uint8()
  external int bmAttributes;

  /// Maximum packet size this endpoint is capable of sending/receiving.
  @ffi.Uint16()
  external int wMaxPacketSize;

  /// Interval for polling endpoint for data transfers.
  @ffi.Uint8()
  external int bInterval;

  /// For audio devices only: the rate at which synchronization feedback is
  /// provided.
  @ffi.Uint8()
  external int bRefresh;

  /// For audio devices only: the address if the synch endpoint
  @ffi.Uint8()
  external int bSynchAddress;

  /// Extra descriptors. If libusb encounters unknown endpoint descriptors, it
  /// will store them here, should you wish to parse them.
  external ffi.Pointer<ffi.UnsignedChar> extra;

  /// Length of the extra descriptors, in bytes. Must be non-negative.
  @ffi.Int()
  external int extra_length;
}

/// A structure representing the standard USB interface descriptor. This
/// descriptor is documented in section 9.6.5 of the USB 3.0 specification. All
/// multiple-byte fields are represented in host-endian format.
final class libusb_interface_descriptor extends ffi.Struct {
  /// Size of this descriptor (in bytes)
  @ffi.Uint8()
  external int bLength;

  /// Descriptor type. Will have value
  /// libusb_descriptor_type::LIBUSB_DT_INTERFACE LIBUSB_DT_INTERFACE in this
  /// context.
  @ffi.Uint8()
  external int bDescriptorType;

  /// Number of this interface
  @ffi.Uint8()
  external int bInterfaceNumber;

  /// Value used to select this alternate setting for this interface
  @ffi.Uint8()
  external int bAlternateSetting;

  /// Number of endpoints used by this interface (excluding the control
  /// endpoint).
  @ffi.Uint8()
  external int bNumEndpoints;

  /// USB-IF class code for this interface. See libusb_class_code.
  @ffi.Uint8()
  external int bInterfaceClass;

  /// USB-IF subclass code for this interface, qualified by the bInterfaceClass
  /// value
  @ffi.Uint8()
  external int bInterfaceSubClass;

  /// USB-IF protocol code for this interface, qualified by the bInterfaceClass
  /// and bInterfaceSubClass values
  @ffi.Uint8()
  external int bInterfaceProtocol;

  /// Index of string descriptor describing this interface
  @ffi.Uint8()
  external int iInterface;

  /// Array of endpoint descriptors. This length of this array is determined by
  /// the bNumEndpoints field.
  external ffi.Pointer<libusb_endpoint_descriptor> endpoint;

  /// Extra descriptors. If libusb encounters unknown interface descriptors, it
  /// will store them here, should you wish to parse them.
  external ffi.Pointer<ffi.UnsignedChar> extra;

  /// Length of the extra descriptors, in bytes. Must be non-negative.
  @ffi.Int()
  external int extra_length;
}

/// A collection of alternate settings for a particular USB interface.
final class libusb_interface extends ffi.Struct {
  /// Array of interface descriptors. The length of this array is determined by
  /// the num_altsetting field.
  external ffi.Pointer<libusb_interface_descriptor> altsetting;

  /// The number of alternate settings that belong to this interface. Must be
  /// non-negative.
  @ffi.Int()
  external int num_altsetting;
}

/// A structure representing the standard USB configuration descriptor. This
/// descriptor is documented in section 9.6.3 of the USB 3.0 specification. All
/// multiple-byte fields are represented in host-endian format.
final class libusb_config_descriptor extends ffi.Struct {
  /// Size of this descriptor (in bytes)
  @ffi.Uint8()
  external int bLength;

  /// Descriptor type. Will have value libusb_descriptor_type::LIBUSB_DT_CONFIG
  /// LIBUSB_DT_CONFIG in this context.
  @ffi.Uint8()
  external int bDescriptorType;

  /// Total length of data returned for this configuration
  @ffi.Uint16()
  external int wTotalLength;

  /// Number of interfaces supported by this configuration
  @ffi.Uint8()
  external int bNumInterfaces;

  /// Identifier value for this configuration
  @ffi.Uint8()
  external int bConfigurationValue;

  /// Index of string descriptor describing this configuration
  @ffi.Uint8()
  external int iConfiguration;

  /// Configuration characteristics
  @ffi.Uint8()
  external int bmAttributes;

  /// Maximum power consumption of the USB device from this bus in this
  /// configuration when the device is fully operation. Expressed in units of 2
  /// mA when the device is operating in high-speed mode and in units of 8 mA
  /// when the device is operating in super-speed mode.
  @ffi.Uint8()
  external int MaxPower;

  /// Array of interfaces supported by this configuration. The length of this
  /// array is determined by the bNumInterfaces field.
  external ffi.Pointer<libusb_interface> interface1;

  /// Extra descriptors. If libusb encounters unknown configuration descriptors,
  /// it will store them here, should you wish to parse them.
  external ffi.Pointer<ffi.UnsignedChar> extra;

  /// Length of the extra descriptors, in bytes. Must be non-negative.
  @ffi.Int()
  external int extra_length;
}

/// Error codes. Most libusb functions return 0 on success or one of these codes
/// on failure. You can call libusb_error_name() to retrieve a string
/// representation of an error code or libusb_strerror() to get an end-user
/// suitable description of an error code.
enum libusb_error {
  /// Success (no error)
  LIBUSB_SUCCESS(0),

  /// Input/output error
  LIBUSB_ERROR_IO(-1),

  /// Invalid parameter
  LIBUSB_ERROR_INVALID_PARAM(-2),

  /// Access denied (insufficient permissions)
  LIBUSB_ERROR_ACCESS(-3),

  /// No such device (it may have been disconnected)
  LIBUSB_ERROR_NO_DEVICE(-4),

  /// Entity not found
  LIBUSB_ERROR_NOT_FOUND(-5),

  /// Resource busy
  LIBUSB_ERROR_BUSY(-6),

  /// Operation timed out
  LIBUSB_ERROR_TIMEOUT(-7),

  /// Overflow
  LIBUSB_ERROR_OVERFLOW(-8),

  /// Pipe error
  LIBUSB_ERROR_PIPE(-9),

  /// System call interrupted (perhaps due to signal)
  LIBUSB_ERROR_INTERRUPTED(-10),

  /// Insufficient memory
  LIBUSB_ERROR_NO_MEM(-11),

  /// Operation not supported or unimplemented on this platform
  LIBUSB_ERROR_NOT_SUPPORTED(-12),

  /// Other error
  LIBUSB_ERROR_OTHER(-99);

  final int value;
  const libusb_error(this.value);

  static libusb_error fromValue(int value) => switch (value) {
    0 => LIBUSB_SUCCESS,
    -1 => LIBUSB_ERROR_IO,
    -2 => LIBUSB_ERROR_INVALID_PARAM,
    -3 => LIBUSB_ERROR_ACCESS,
    -4 => LIBUSB_ERROR_NO_DEVICE,
    -5 => LIBUSB_ERROR_NOT_FOUND,
    -6 => LIBUSB_ERROR_BUSY,
    -7 => LIBUSB_ERROR_TIMEOUT,
    -8 => LIBUSB_ERROR_OVERFLOW,
    -9 => LIBUSB_ERROR_PIPE,
    -10 => LIBUSB_ERROR_INTERRUPTED,
    -11 => LIBUSB_ERROR_NO_MEM,
    -12 => LIBUSB_ERROR_NOT_SUPPORTED,
    -99 => LIBUSB_ERROR_OTHER,
    _ => throw ArgumentError("Unknown value for libusb_error: $value"),
  };
}

/// Transfer type
enum libusb_transfer_type {
  /// Control transfer
  LIBUSB_TRANSFER_TYPE_CONTROL(0),

  /// Isochronous transfer
  LIBUSB_TRANSFER_TYPE_ISOCHRONOUS(1),

  /// Bulk transfer
  LIBUSB_TRANSFER_TYPE_BULK(2),

  /// Interrupt transfer
  LIBUSB_TRANSFER_TYPE_INTERRUPT(3),

  /// Bulk stream transfer
  LIBUSB_TRANSFER_TYPE_BULK_STREAM(4);

  final int value;
  const libusb_transfer_type(this.value);

  static libusb_transfer_type fromValue(int value) => switch (value) {
    0 => LIBUSB_TRANSFER_TYPE_CONTROL,
    1 => LIBUSB_TRANSFER_TYPE_ISOCHRONOUS,
    2 => LIBUSB_TRANSFER_TYPE_BULK,
    3 => LIBUSB_TRANSFER_TYPE_INTERRUPT,
    4 => LIBUSB_TRANSFER_TYPE_BULK_STREAM,
    _ => throw ArgumentError("Unknown value for libusb_transfer_type: $value"),
  };
}

final class libusb_context extends ffi.Opaque {}

/// Structure used for setting options through libusb_init_context.
final class libusb_init_option extends ffi.Struct {
  /// Which option to set
  @ffi.UnsignedInt()
  external int optionAsInt;

  libusb_option get option => libusb_option.fromValue(optionAsInt);

  external UnnamedUnion1 value;
}

/// Available option values for libusb_set_option() and libusb_init_context().
enum libusb_option {
  /// Set the log message verbosity.
  LIBUSB_OPTION_LOG_LEVEL(0),

  /// Use the UsbDk backend for a specific context, if available.
  LIBUSB_OPTION_USE_USBDK(1),

  /// Do not scan for devices
  LIBUSB_OPTION_NO_DEVICE_DISCOVERY(2),

  /// Set the context log callback function.
  LIBUSB_OPTION_LOG_CB(3),
  LIBUSB_OPTION_MAX(4);

  final int value;
  const libusb_option(this.value);

  static libusb_option fromValue(int value) => switch (value) {
    0 => LIBUSB_OPTION_LOG_LEVEL,
    1 => LIBUSB_OPTION_USE_USBDK,
    2 => LIBUSB_OPTION_NO_DEVICE_DISCOVERY,
    3 => LIBUSB_OPTION_LOG_CB,
    4 => LIBUSB_OPTION_MAX,
    _ => throw ArgumentError("Unknown value for libusb_option: $value"),
  };
}

/// An integer value used by the option (if applicable).
final class UnnamedUnion1 extends ffi.Union {
  @ffi.Int()
  external int ival;

  external libusb_log_cb log_cbval;
}

/// Callback function for handling log messages.
typedef libusb_log_cb = ffi.Pointer<ffi.NativeFunction<libusb_log_cbFunction>>;
typedef libusb_log_cbFunction =
    ffi.Void Function(
      ffi.Pointer<libusb_context> ctx,
      ffi.UnsignedInt level,
      ffi.Pointer<ffi.Char> str,
    );
typedef Dartlibusb_log_cbFunction =
    void Function(
      ffi.Pointer<libusb_context> ctx,
      libusb_log_level level,
      ffi.Pointer<ffi.Char> str,
    );

/// Log message levels.
enum libusb_log_level {
  /// (0) : No messages ever emitted by the library (default)
  LIBUSB_LOG_LEVEL_NONE(0),

  /// (1) : Error messages are emitted
  LIBUSB_LOG_LEVEL_ERROR(1),

  /// (2) : Warning and error messages are emitted
  LIBUSB_LOG_LEVEL_WARNING(2),

  /// (3) : Informational, warning and error messages are emitted
  LIBUSB_LOG_LEVEL_INFO(3),

  /// (4) : All messages are emitted
  LIBUSB_LOG_LEVEL_DEBUG(4);

  final int value;
  const libusb_log_level(this.value);

  static libusb_log_level fromValue(int value) => switch (value) {
    0 => LIBUSB_LOG_LEVEL_NONE,
    1 => LIBUSB_LOG_LEVEL_ERROR,
    2 => LIBUSB_LOG_LEVEL_WARNING,
    3 => LIBUSB_LOG_LEVEL_INFO,
    4 => LIBUSB_LOG_LEVEL_DEBUG,
    _ => throw ArgumentError("Unknown value for libusb_log_level: $value"),
  };
}

typedef ssize_t = __darwin_ssize_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;

final class libusb_device extends ffi.Opaque {}

final class libusb_device_handle extends ffi.Opaque {}
