// // Copyright (c) 2026 StampCommit. All rights reserved.
// // GENERATED FILE — DO NOT EDIT.
// // Regenerate with: dart run pigeon --input pigeons/usb_messages.dart
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// One USB device returned by [UsbHostApi.enumerate].
class UsbDeviceRecord {
  UsbDeviceRecord({
    required this.vendorId,
    required this.productId,
    required this.path,
    required this.hasPermission,
    this.manufacturer,
    this.product,
    this.serialNumber,
    this.interfaceNumber,
    this.bulkInEndpoint,
    this.bulkOutEndpoint,
    this.wMaxPacketSizeOut,
    this.driverBinding,
  });

  /// Vendor ID (0x0A5F for Zebra).
  int vendorId;

  /// Product ID.
  int productId;

  /// Platform-opaque identifier used for subsequent calls.
  /// Android: `/dev/bus/usb/001/004`. macOS: IOKit path. Windows: `\\?\USB#VID_...`.
  String path;

  /// Android-relevant. True on macOS/Windows (permission model is per-app, not per-device).
  bool hasPermission;

  String? manufacturer;

  String? product;

  String? serialNumber;

  /// Printer-class interface index (`bInterfaceClass == 0x07`). Null if no such
  /// interface exists on the device.
  int? interfaceNumber;

  /// Bulk IN endpoint address (with direction bit).
  int? bulkInEndpoint;

  /// Bulk OUT endpoint address.
  int? bulkOutEndpoint;

  /// wMaxPacketSize of the bulk-OUT endpoint. Drives auto chunk size.
  int? wMaxPacketSizeOut;

  /// Windows-only. One of "WINUSB", "USBPRINT", "OTHER". Null on other platforms.
  String? driverBinding;

  Object encode() {
    return <Object?>[
      vendorId,
      productId,
      path,
      hasPermission,
      manufacturer,
      product,
      serialNumber,
      interfaceNumber,
      bulkInEndpoint,
      bulkOutEndpoint,
      wMaxPacketSizeOut,
      driverBinding,
    ];
  }

  static UsbDeviceRecord decode(Object result) {
    result as List<Object?>;
    return UsbDeviceRecord(
      vendorId: result[0]! as int,
      productId: result[1]! as int,
      path: result[2]! as String,
      hasPermission: result[3]! as bool,
      manufacturer: result[4] as String?,
      product: result[5] as String?,
      serialNumber: result[6] as String?,
      interfaceNumber: result[7] as int?,
      bulkInEndpoint: result[8] as int?,
      bulkOutEndpoint: result[9] as int?,
      wMaxPacketSizeOut: result[10] as int?,
      driverBinding: result[11] as String?,
    );
  }
}

/// Filter passed to [UsbHostApi.enumerate].
class UsbEnumerateFilter {
  UsbEnumerateFilter({
    this.vendorId,
    this.includeDescriptorStrings = true,
  });

  /// If non-null, return only devices with this vendor ID.
  int? vendorId;

  /// Reading descriptor strings is slow on Windows (~10-50ms/device).
  /// Set false during hot-plug re-enumeration where latency matters.
  bool includeDescriptorStrings;

  Object encode() {
    return <Object?>[
      vendorId,
      includeDescriptorStrings,
    ];
  }

  static UsbEnumerateFilter decode(Object result) {
    result as List<Object?>;
    return UsbEnumerateFilter(
      vendorId: result[0] as int?,
      includeDescriptorStrings: result[1]! as bool,
    );
  }
}

/// Result of a successful [UsbHostApi.openForFfi] call. The Dart FFI layer
/// takes over I/O from here.
class UsbOpenResult {
  UsbOpenResult({
    required this.platformHandle,
    required this.vendorId,
    required this.productId,
    this.serialNumber,
    required this.claimedInterfaceNumber,
    required this.bulkInEndpoint,
    required this.bulkOutEndpoint,
    required this.wMaxPacketSizeOut,
  });

  /// Android: file descriptor from `UsbDeviceConnection.getFileDescriptor()`.
  /// macOS/Windows: 0 (FFI matches the device via VID+PID+serial).
  int platformHandle;

  int vendorId;

  int productId;

  String? serialNumber;

  /// Interface index that the native side has claimed.
  int claimedInterfaceNumber;

  int bulkInEndpoint;

  int bulkOutEndpoint;

  int wMaxPacketSizeOut;

  Object encode() {
    return <Object?>[
      platformHandle,
      vendorId,
      productId,
      serialNumber,
      claimedInterfaceNumber,
      bulkInEndpoint,
      bulkOutEndpoint,
      wMaxPacketSizeOut,
    ];
  }

  static UsbOpenResult decode(Object result) {
    result as List<Object?>;
    return UsbOpenResult(
      platformHandle: result[0]! as int,
      vendorId: result[1]! as int,
      productId: result[2]! as int,
      serialNumber: result[3] as String?,
      claimedInterfaceNumber: result[4]! as int,
      bulkInEndpoint: result[5]! as int,
      bulkOutEndpoint: result[6]! as int,
      wMaxPacketSizeOut: result[7]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is UsbDeviceRecord) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is UsbEnumerateFilter) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is UsbOpenResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return UsbDeviceRecord.decode(readValue(buffer)!);
      case 130: 
        return UsbEnumerateFilter.decode(readValue(buffer)!);
      case 131: 
        return UsbOpenResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// USB host API — lifecycle only. Bulk I/O happens via Dart FFI directly to
/// libusb; channel hops would be too expensive for the hot path.
class UsbHostApi {
  /// Constructor for [UsbHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UsbHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Quick capability probe. False on iOS and on desktops without libusb.
  Future<bool> isSupported() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.isSupported$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Snapshot enumeration. Returns a complete list (no streaming).
  Future<List<UsbDeviceRecord>> enumerate(UsbEnumerateFilter filter) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.enumerate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[filter]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<UsbDeviceRecord>();
    }
  }

  /// Android: `UsbManager.hasPermission(device)`. Other: always true.
  Future<bool> hasPermission(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.hasPermission$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[path]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Android: triggers system dialog; resolves when user responds.
  /// Other: resolves true immediately.
  Future<bool> requestPermission(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.requestPermission$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[path]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Claims the printer-class interface on Android (fd-based libusb handoff).
  /// On macOS/Windows, returns metadata so Dart FFI can call libusb_open.
  /// Throws on permission denied, device busy, device disappeared, etc.
  Future<UsbOpenResult> openForFfi(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.openForFfi$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[path]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as UsbOpenResult?)!;
    }
  }

  /// Final cleanup after Dart FFI has released and closed the libusb handle.
  /// Android: closes the retained `UsbDeviceConnection`. Other: no-op.
  /// Must be idempotent.
  Future<void> closeAfterFfi(String path) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_zpl_printer.UsbHostApi.closeAfterFfi$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[path]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
